spring.application.name=Movie Review
server.port=9090

spring.mongodb.uri=mongodb+srv://user1:11753@spring-mongo.dgdoyrn.mongodb.net/movie_review_db?appName=spring-mongo



jwt.secret=ChangeThisToALongRandomSecretKeyBeforeProduction_MinAtLeast32Bytes
jwt.expiration=86400000